/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ConditionScopeProvider extends AbstractConditionScopeProvider {

}
