/**
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.condition.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import zbr.test.condition.condition.Condition;
import zbr.test.condition.condition.ConditionPackage;
import zbr.test.condition.condition.ConditionalExpression;
import zbr.test.condition.condition.LogicalOpeartor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conditional Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link zbr.test.condition.condition.impl.ConditionalExpressionImpl#getConditionParam <em>Condition Param</em>}</li>
 *   <li>{@link zbr.test.condition.condition.impl.ConditionalExpressionImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link zbr.test.condition.condition.impl.ConditionalExpressionImpl#getAftetrSymbol <em>Aftetr Symbol</em>}</li>
 *   <li>{@link zbr.test.condition.condition.impl.ConditionalExpressionImpl#getBeforeSymbol <em>Before Symbol</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConditionalExpressionImpl extends MinimalEObjectImpl.Container implements ConditionalExpression
{
	/**
	 * The cached value of the '{@link #getConditionParam() <em>Condition Param</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getConditionParam()
	 * @generated
	 * @ordered
	 */
	protected Condition conditionParam;

	/**
	 * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCondition()
	 * @generated
	 * @ordered
	 */
	protected Condition condition;

	/**
	 * The cached value of the '{@link #getAftetrSymbol() <em>Aftetr Symbol</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAftetrSymbol()
	 * @generated
	 * @ordered
	 */
	protected LogicalOpeartor aftetrSymbol;

	/**
	 * The cached value of the '{@link #getBeforeSymbol() <em>Before Symbol</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getBeforeSymbol()
	 * @generated
	 * @ordered
	 */
	protected LogicalOpeartor beforeSymbol;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionalExpressionImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return ConditionPackage.Literals.CONDITIONAL_EXPRESSION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Condition getConditionParam()
	{
		return conditionParam;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetConditionParam(Condition newConditionParam, NotificationChain msgs)
	{
		Condition oldConditionParam = conditionParam;
		conditionParam = newConditionParam;
		if (eNotificationRequired())
		{
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM, oldConditionParam, newConditionParam);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setConditionParam(Condition newConditionParam)
	{
		if (newConditionParam != conditionParam)
		{
			NotificationChain msgs = null;
			if (conditionParam != null)
				msgs = ((InternalEObject)conditionParam).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM, null, msgs);
			if (newConditionParam != null)
				msgs = ((InternalEObject)newConditionParam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM, null, msgs);
			msgs = basicSetConditionParam(newConditionParam, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM, newConditionParam, newConditionParam));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Condition getCondition()
	{
		return condition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetCondition(Condition newCondition, NotificationChain msgs)
	{
		Condition oldCondition = condition;
		condition = newCondition;
		if (eNotificationRequired())
		{
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION, oldCondition, newCondition);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCondition(Condition newCondition)
	{
		if (newCondition != condition)
		{
			NotificationChain msgs = null;
			if (condition != null)
				msgs = ((InternalEObject)condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION, null, msgs);
			if (newCondition != null)
				msgs = ((InternalEObject)newCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION, null, msgs);
			msgs = basicSetCondition(newCondition, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION, newCondition, newCondition));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public LogicalOpeartor getAftetrSymbol()
	{
		return aftetrSymbol;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetAftetrSymbol(LogicalOpeartor newAftetrSymbol, NotificationChain msgs)
	{
		LogicalOpeartor oldAftetrSymbol = aftetrSymbol;
		aftetrSymbol = newAftetrSymbol;
		if (eNotificationRequired())
		{
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL, oldAftetrSymbol, newAftetrSymbol);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setAftetrSymbol(LogicalOpeartor newAftetrSymbol)
	{
		if (newAftetrSymbol != aftetrSymbol)
		{
			NotificationChain msgs = null;
			if (aftetrSymbol != null)
				msgs = ((InternalEObject)aftetrSymbol).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL, null, msgs);
			if (newAftetrSymbol != null)
				msgs = ((InternalEObject)newAftetrSymbol).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL, null, msgs);
			msgs = basicSetAftetrSymbol(newAftetrSymbol, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL, newAftetrSymbol, newAftetrSymbol));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public LogicalOpeartor getBeforeSymbol()
	{
		return beforeSymbol;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetBeforeSymbol(LogicalOpeartor newBeforeSymbol, NotificationChain msgs)
	{
		LogicalOpeartor oldBeforeSymbol = beforeSymbol;
		beforeSymbol = newBeforeSymbol;
		if (eNotificationRequired())
		{
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL, oldBeforeSymbol, newBeforeSymbol);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setBeforeSymbol(LogicalOpeartor newBeforeSymbol)
	{
		if (newBeforeSymbol != beforeSymbol)
		{
			NotificationChain msgs = null;
			if (beforeSymbol != null)
				msgs = ((InternalEObject)beforeSymbol).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL, null, msgs);
			if (newBeforeSymbol != null)
				msgs = ((InternalEObject)newBeforeSymbol).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL, null, msgs);
			msgs = basicSetBeforeSymbol(newBeforeSymbol, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL, newBeforeSymbol, newBeforeSymbol));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
	{
		switch (featureID)
		{
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM:
				return basicSetConditionParam(null, msgs);
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION:
				return basicSetCondition(null, msgs);
			case ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL:
				return basicSetAftetrSymbol(null, msgs);
			case ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL:
				return basicSetBeforeSymbol(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType)
	{
		switch (featureID)
		{
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM:
				return getConditionParam();
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION:
				return getCondition();
			case ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL:
				return getAftetrSymbol();
			case ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL:
				return getBeforeSymbol();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue)
	{
		switch (featureID)
		{
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM:
				setConditionParam((Condition)newValue);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION:
				setCondition((Condition)newValue);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL:
				setAftetrSymbol((LogicalOpeartor)newValue);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL:
				setBeforeSymbol((LogicalOpeartor)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID)
	{
		switch (featureID)
		{
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM:
				setConditionParam((Condition)null);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION:
				setCondition((Condition)null);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL:
				setAftetrSymbol((LogicalOpeartor)null);
				return;
			case ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL:
				setBeforeSymbol((LogicalOpeartor)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID)
	{
		switch (featureID)
		{
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION_PARAM:
				return conditionParam != null;
			case ConditionPackage.CONDITIONAL_EXPRESSION__CONDITION:
				return condition != null;
			case ConditionPackage.CONDITIONAL_EXPRESSION__AFTETR_SYMBOL:
				return aftetrSymbol != null;
			case ConditionPackage.CONDITIONAL_EXPRESSION__BEFORE_SYMBOL:
				return beforeSymbol != null;
		}
		return super.eIsSet(featureID);
	}

} //ConditionalExpressionImpl
