/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import zbr.test.condition.ui.internal.ConditionActivator;

public class ConditionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConditionActivator.getInstance().getInjector("zbr.test.condition.Condition");
	}

}
