/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConditionUiModule extends AbstractConditionUiModule {

	public ConditionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
