/**
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.condition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link zbr.test.condition.condition.MessageContent#getContent <em>Content</em>}</li>
 *   <li>{@link zbr.test.condition.condition.MessageContent#getTimeUnit <em>Time Unit</em>}</li>
 *   <li>{@link zbr.test.condition.condition.MessageContent#getValue <em>Value</em>}</li>
 *   <li>{@link zbr.test.condition.condition.MessageContent#getComparisonOperator <em>Comparison Operator</em>}</li>
 * </ul>
 *
 * @see zbr.test.condition.condition.ConditionPackage#getMessageContent()
 * @model
 * @generated
 */
public interface MessageContent extends Term
{
	/**
	 * Returns the value of the '<em><b>Content</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Content</em>' attribute.
	 * @see #setContent(String)
	 * @see zbr.test.condition.condition.ConditionPackage#getMessageContent_Content()
	 * @model
	 * @generated
	 */
	String getContent();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.MessageContent#getContent <em>Content</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Content</em>' attribute.
	 * @see #getContent()
	 * @generated
	 */
	void setContent(String value);

	/**
	 * Returns the value of the '<em><b>Time Unit</b></em>' attribute.
	 * The literals are from the enumeration {@link zbr.test.condition.condition.TimeUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Time Unit</em>' attribute.
	 * @see zbr.test.condition.condition.TimeUnit
	 * @see #setTimeUnit(TimeUnit)
	 * @see zbr.test.condition.condition.ConditionPackage#getMessageContent_TimeUnit()
	 * @model
	 * @generated
	 */
	TimeUnit getTimeUnit();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.MessageContent#getTimeUnit <em>Time Unit</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Time Unit</em>' attribute.
	 * @see zbr.test.condition.condition.TimeUnit
	 * @see #getTimeUnit()
	 * @generated
	 */
	void setTimeUnit(TimeUnit value);

	/**
	 * Returns the value of the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Value</em>' attribute.
	 * @see #setValue(String)
	 * @see zbr.test.condition.condition.ConditionPackage#getMessageContent_Value()
	 * @model
	 * @generated
	 */
	String getValue();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.MessageContent#getValue <em>Value</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Value</em>' attribute.
	 * @see #getValue()
	 * @generated
	 */
	void setValue(String value);

	/**
	 * Returns the value of the '<em><b>Comparison Operator</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Comparison Operator</em>' containment reference.
	 * @see #setComparisonOperator(ComparisonOperator)
	 * @see zbr.test.condition.condition.ConditionPackage#getMessageContent_ComparisonOperator()
	 * @model containment="true"
	 * @generated
	 */
	ComparisonOperator getComparisonOperator();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.MessageContent#getComparisonOperator <em>Comparison Operator</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Comparison Operator</em>' containment reference.
	 * @see #getComparisonOperator()
	 * @generated
	 */
	void setComparisonOperator(ComparisonOperator value);

} // MessageContent
