/**
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.condition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Session Interval</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link zbr.test.condition.condition.SessionInterval#getFrequency <em>Frequency</em>}</li>
 *   <li>{@link zbr.test.condition.condition.SessionInterval#getTimeUnit <em>Time Unit</em>}</li>
 *   <li>{@link zbr.test.condition.condition.SessionInterval#getMessagecontent <em>Messagecontent</em>}</li>
 *   <li>{@link zbr.test.condition.condition.SessionInterval#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see zbr.test.condition.condition.ConditionPackage#getSessionInterval()
 * @model
 * @generated
 */
public interface SessionInterval extends Term
{
	/**
	 * Returns the value of the '<em><b>Frequency</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Frequency</em>' attribute.
	 * @see #setFrequency(int)
	 * @see zbr.test.condition.condition.ConditionPackage#getSessionInterval_Frequency()
	 * @model
	 * @generated
	 */
	int getFrequency();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.SessionInterval#getFrequency <em>Frequency</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Frequency</em>' attribute.
	 * @see #getFrequency()
	 * @generated
	 */
	void setFrequency(int value);

	/**
	 * Returns the value of the '<em><b>Time Unit</b></em>' attribute.
	 * The literals are from the enumeration {@link zbr.test.condition.condition.TimeUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Time Unit</em>' attribute.
	 * @see zbr.test.condition.condition.TimeUnit
	 * @see #setTimeUnit(TimeUnit)
	 * @see zbr.test.condition.condition.ConditionPackage#getSessionInterval_TimeUnit()
	 * @model
	 * @generated
	 */
	TimeUnit getTimeUnit();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.SessionInterval#getTimeUnit <em>Time Unit</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Time Unit</em>' attribute.
	 * @see zbr.test.condition.condition.TimeUnit
	 * @see #getTimeUnit()
	 * @generated
	 */
	void setTimeUnit(TimeUnit value);

	/**
	 * Returns the value of the '<em><b>Messagecontent</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Messagecontent</em>' containment reference.
	 * @see #setMessagecontent(MessageContent)
	 * @see zbr.test.condition.condition.ConditionPackage#getSessionInterval_Messagecontent()
	 * @model containment="true"
	 * @generated
	 */
	MessageContent getMessagecontent();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.SessionInterval#getMessagecontent <em>Messagecontent</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Messagecontent</em>' containment reference.
	 * @see #getMessagecontent()
	 * @generated
	 */
	void setMessagecontent(MessageContent value);

	/**
	 * Returns the value of the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Value</em>' attribute.
	 * @see #setValue(String)
	 * @see zbr.test.condition.condition.ConditionPackage#getSessionInterval_Value()
	 * @model
	 * @generated
	 */
	String getValue();

	/**
	 * Sets the value of the '{@link zbr.test.condition.condition.SessionInterval#getValue <em>Value</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Value</em>' attribute.
	 * @see #getValue()
	 * @generated
	 */
	void setValue(String value);

} // SessionInterval
