/**
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.condition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see zbr.test.condition.condition.ConditionPackage#getTerm()
 * @model
 * @generated
 */
public interface Term extends Condition
{
} // Term
