/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import zbr.test.condition.ConditionRuntimeModule;
import zbr.test.condition.ConditionStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConditionIdeSetup extends ConditionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConditionRuntimeModule(), new ConditionIdeModule()));
	}
	
}
