/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConditionRuntimeModule extends AbstractConditionRuntimeModule {
}
