/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import zbr.test.condition.parser.antlr.internal.InternalConditionParser;
import zbr.test.condition.services.ConditionGrammarAccess;

public class ConditionParser extends AbstractAntlrParser {

	@Inject
	private ConditionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConditionParser createParser(XtextTokenStream stream) {
		return new InternalConditionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ConditionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConditionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
