/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import zbr.test.condition.ui.internal.ConditionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConditionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ConditionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ConditionActivator activator = ConditionActivator.getInstance();
		return activator != null ? activator.getInjector(ConditionActivator.ZBR_TEST_CONDITION_CONDITION) : null;
	}

}
