<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="condition" nsURI="http://www.test.zbr/condition/Condition" nsPrefix="condition">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalExpression"
        upperBound="-1" eType="#//ConditionalExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryTermOperator" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryTermOperator" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeCondition" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionInterval" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagecontent" eType="#//MessageContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeInterval" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timeout" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeekDaysInterval" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="#//WeekDay"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="#//WeekDay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxNumberOfOperation" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationsNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="#//TimeUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="SECOND"/>
    <eLiterals name="MINUTE" value="1"/>
    <eLiterals name="HOUR" value="2"/>
    <eLiterals name="DAY" value="3"/>
    <eLiterals name="WEEK" value="4"/>
    <eLiterals name="MONTH" value="5" literal="MONTH"/>
    <eLiterals name="YEAR" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SessionStatus">
    <eLiterals name="CLOSED"/>
    <eLiterals name="OPEN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operation">
    <eLiterals name="PUSH"/>
    <eLiterals name="POLL" value="1"/>
    <eLiterals name="WRITE" value="2"/>
    <eLiterals name="READ" value="3"/>
    <eLiterals name="REQUEST" value="4"/>
    <eLiterals name="RESPONSE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDay">
    <eLiterals name="SUNDAY"/>
    <eLiterals name="MONDAY" value="1"/>
    <eLiterals name="TUESDAY" value="2"/>
    <eLiterals name="WEDNESDAY" value="3"/>
    <eLiterals name="THURSDAY" value="4"/>
    <eLiterals name="FRIDAY" value="5"/>
    <eLiterals name="SATURDAY" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageContent" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisonOperator" eType="#//ComparisonOperator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionParam" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aftetrSymbol" eType="#//LogicalOpeartor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeSymbol" eType="#//LogicalOpeartor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalOpeartor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
