/**
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.condition;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see zbr.test.condition.condition.ConditionPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
