/*
 * generated by Xtext 2.28.0
 */
package zbr.test.condition.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractConditionScopeProvider extends DelegatingScopeProvider {
}
